language: ruby
cache: bundler
rvm:
  - "2.1.2"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database modera_dummy_test;' -U postgres
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle exec rake db:migrate
